# RuboCop Default Config: https://github.com/rubocop/rubocop/blob/master/config/default.yml

plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.4

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/MultipleComparison:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/EndOfLine:
  EnforcedStyle: lf

Naming/MethodParameterName:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
